apiVersion: v1
description: A Magda forked version of MinIO Helm chart
name: minio
version: 7.1.2
appVersion: master
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: Jacky Jiang
  email: contact@magda.io
